version: 2

jobs:
    "python-3.6":
        docker:
            - image: circleci/python:3.6-stretch-browsers
        steps:
            - checkout
            - run: pip install tox && tox

workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
