version: 2

jobs:
    build:
        docker:
            - image: python:3.6
        steps:
            - checkout
    test:
        steps:
            - run: pip install tox && tox

workflows:
    version: 2
    build-and-test:
        jobs:
            - build
            - test:
                requires:
                    - build
